### ISSUE TITLE
Not working on some SamsungBrowser devices

### ISSUE THREAD

**Issue by loris** [andyearnshaw/Intl.js#170]
As reported over at the [FT polyfill repo](https://github.com/Financial-Times/polyfill-service/pull/671#issuecomment-218724622), I got React Intl errors (`[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.`) reported for all visitors using devices where the UA contains `SamsungBrowser`.
At first, I thought it was a UA sniffing issue (ie, polyfill.io detects the browser as a Chrome runtime not needing any Intl polyfill), but I got my hands on a test device (`SamsungBrowser/3.3 Chrome/38.0.2125.102`) and test that snippet where the Intl polyfill is supposed to be always injected:

```
 <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en|always"></script>
 <script>
  window.alert(window.Intl);
</script>
```

The alert displays `undefined`

If I change the URL to another polyfill CDN `http://polyfills.yahooapis.com/polyfill.min.js?version=2.1.9&features=Intl,Clocale-data-en-US` then, the alert correctly displays `[object Object]`

**Comment by caridy** [comment]
should be fixed with today's release @loris, will let you know.

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/issues/171

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.1

**Comment by MasDevProject** [comment]
Is it available also on cdn?

**Comment by caridy** [comment]
This repo only produces the npm version of the polyfill, there is another process to update the Financial Times Polyfill service to serve the latest version from npm, in this case, we are doing it here: https://github.com/Financial-Times/polyfill-service/pull/698

**Comment by MasDevProject** [comment]
@caridy 
Just installed Intl ( `npm install intl` `"name": "intl",  "version": "1.2.2",` ) and added it to my index ( `<script src="Intl.min.js"></script>` ) but I get the same error.

**Comment by caridy** [comment]
@MasDevProject can you provide a very small repro case? what exactly is the error, and in which line? can you use `src="Intl.js"` instead, so you get the line number, and the error details. Unfortunately I don't have a Samsung device to test this.

**Comment by MasDevProject** [comment]
I'm using it with angular2.
This is the stacktrace of the exception I got: http://i.stack.imgur.com/rx2dW.png

This is my index.html: https://gist.github.com/MasDevProject/0ecd89b111529d8e00e9a2625b97461b

**Comment by caridy** [comment]
open the browser console and type:

```
console.log(window.Intl);
console.log(window.IntlPolyfill);
```

and let me know if they are defined.

**Comment by MasDevProject** [comment]
@caridy thanks for the instructions!
Using Chrome both variables are Defined,
using the Samsung browser window.Intl is UNdefined, window.IntlPolyfill is Defined.

Hope this helps

**Comment by caridy** [comment]
If `window.IntlPolyfill` is set, then the following line https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.js#L3810 is doing its job. The remaining question is to investigate why the block of code above that line (https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.js#L3810) doesn't work:


```
    // hack to export the polyfill as global Intl if needed
    if (typeof Intl !== 'undefined') {
        try {
            Intl = Intl$1;
            Intl$1.__applyLocaleSensitivePrototypes();
        } catch (e) {
            // can be read only property
        }
    }
```

Maybe that try/catch is swallowing the error. Alternative, we could force the detection to happen on the `window` variable for browsers, by doing:

```
    // hack to export the polyfill as global Intl if needed
    if (typeof window.Intl !== 'undefined') {
        try {
            window.Intl = Intl$1;
            Intl$1.__applyLocaleSensitivePrototypes();
        } catch (e) {
            // can be read only property
        }
    }
```

**Comment by MasDevProject** [comment]
Thanks @caridy for your work.
Just tried with
`if (typeof window.Intl !== 'undefined') {
        try {
            window.Intl = Intl$1;
            Intl$1.__applyLocaleSensitivePrototypes();
        } catch (e) {
            // can be read only property
        }
    }`

But the problem persists, I also put an alert into the catch but it's never called.
I also noticed that `if (typeof window.Intl !== 'undefined')` return falso, so the code inside is not called

**Comment by caridy** [comment]
oh wow! how is that this condition is incorrect! I will fix and release later today.

**Comment by caridy** [comment]
Definitely an issue introduced by @watilde recently. Fixed by 86387c730e7129dfbf73dc08a5b0b393fc7ea784, and added some tests to prevent this from happening again 4d75e49f1caa16e01be28236ae2af391fd375028

**Comment by caridy** [comment]
+ intl@1.2.3 

@MasDevProject let me know if you have any issue with the new version.

**Comment by MasDevProject** [comment]
@caridy 
the 1.2.3 version does not work. This is the correct clausule:
`if (typeof Intl === 'undefined') {
        try {
            window.Intl = Intl$1;
            Intl$1.__applyLocaleSensitivePrototypes();
        } catch (e) {
            // can be read only property
        }
    }`

**Comment by guilhermesimoes** [comment]
Yup, `1.2.3` is still not polyfilling the browser correctly.

**Comment by ying22** [comment]
I tested this in Safari too. It has to be:
`window.Intl = Intl$1;`

This does not work:
`Int = Intl$1;`

**Comment by caridy** [comment]
Alright, I got a chance to debug this, and you're both right. The reason is this line: https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.js#L5

by having 'use strict', that prevent us from defining and implicit global. this bug was introduced when we moved to modules, will release a patch later today.

**Comment by caridy** [comment]
fixed by 54ef5de115db96482a20b3b218c8ced86c6c81a3

released as intl@1.2.4
