### ISSUE TITLE
Duplicated '月' character in Chinese date formatters

### ISSUE THREAD

**Issue by clarle** [andyearnshaw/Intl.js#69]
In the generated JSON locale files, it looks like Chinese is behaving a bit strangely.

Because the Chinese months are using `long`, we end up getting something like this when rendering it out:

2014年 六月月 19日 星期四

The '月' character for month is duplicated, when it really should be:

2014年 六月 19日 星期四

Or even better:

2014年 6月 19日 星期四

The month format should probably be switched out to `narrow` or `numeric` instead of `long` instead, or have the additional '月' removed in the formatter here:

https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/zh-Hans.json#L33-L39

Repro:
```js
require('intl');
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var df = new Intl.DateTimeFormat('zh', { year: "numeric", month: "long", day: "numeric", weekday: "long"});

df.format(date);
```

Chrome returns:
`2012年12月19日星期三`

Intl.js returns:
`2012年十二月月19日星期三`

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/pull/85

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, help us to test it...

**Comment by okuryu** [comment]
I'm trying out `intl@1.0.0-rc-1`, it seems to be strange.

Node 0.10.38:

```
> require("intl")
{ __localeSensitiveProtos:
   { Number: { toLocaleString: [Function] },
     Date:
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } },
  default: [Circular] }
> new Intl.DateTimeFormat("ja", {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(new Date())
'2015年6月月11日木曜日'
```

Node 0.12.4:

```
> require("intl")
{ __localeSensitiveProtos:
   { Number: { toLocaleString: [Function] },
     Date:
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } },
  default: [Circular] }
> new Intl.DateTimeFormat("ja", {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(new Date())
'2015 M06 11, Thu'
```

**Comment by caridy** [comment]
@okuryu try using `IntlPolyfill.DateTimeFormat()` to make sure that the polyfill is what you're actually testing.

**Comment by okuryu** [comment]
Oops! Sorry for my bad. :sob: But this issue still occurs.

Node 0.10.38:

```
> new IntlPolyfill.DateTimeFormat("ja", {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(new Date())
'2015年6月月11日木曜日'
```

Node 0.12.4:

```
> new IntlPolyfill.DateTimeFormat("ja", {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(new Date())
'2015年6月月11日木曜日'
```

**Comment by caridy** [comment]
@okuryu remember that I can't read Japanese. What exactly is the problem? clearly, the native Intl in `Node 0.12.4` is producing something different than the polyfill, but which one is the correct one?

**Comment by okuryu** [comment]
@caridy Expected value is `'2015年6月11日木曜日'`. Chrome returns this expected value, it's correct. Result of Native Intl in Node 0.12 also isn't correct, my guess it's due to it doesn't has locale data other than English as default. Anyway, this issue will be resolved when fixed Intl.js.

**Comment by caridy** [comment]
we should check cldr formatter, I suspect that is the root of the problem.

**Comment by deddu** [comment]
Any update on this issue? Anything I can do to help?

**Comment by caridy** [comment]
@deddu can you try this branch: https://github.com/andyearnshaw/Intl.js/pull/146

**Comment by deddu** [comment]
@caridy sure thing. 
I checked out the branch and started the build. The build succeeded but I'm having the following issue when starting my server:
```
Intl.js/lib/cldr.js:349
                .replace('{0}', timeRelatedFormats[i].extendedPattern)
                ^

TypeError: Cannot read property 'replace' of undefined
```
It seems there's some dep that might be missing or not updated in the package.json. 
Thoughs?

**Comment by caridy** [comment]
PR #146 fixes part of the problem, but not all. Can you try again with intl@1.1.0?

**Comment by okuryu** [comment]
I've tried intl@1.1.0 with Node.js v0.10.42, it seems not to fixed.

```
> require("intl")
{ __localeSensitiveProtos:
   { Number: { toLocaleString: [Function] },
     Date:
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } },
  default: [Circular] }
> new Intl.DateTimeFormat('ja', {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(Date.now())
'2016年2月月13日土曜日'
```

On Node.js v0.12+ (includes v4, v5), I see weird results with intl@1.0.0 and intl@1.1.0 as follows. I'm not sure it's a bug on Intl.js or Node.js..

```
> require('intl')
{ __localeSensitiveProtos:
   { Number: { toLocaleString: [Function] },
     Date:
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } },
  default: [Circular] }
> new Intl.DateTimeFormat('ja', {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(Date.now())
'2016 M02 13, Sat'
```

**Comment by caridy** [comment]
@okuryu thanks. I was suspecting that. As for the issue with node, it is just like your node is using the Intl from v8 but with english local only.

**Comment by ngduc** [comment]
+1 facing the same issue with Japanese: day="numeric" month="short" year="numeric"
it returns 2 '月' characters like: 2016年3月月9日
intl version: 1.1.0
Is it fixed yet? Thanks.

**Comment by caridy** [comment]
@ngduc we plan to fix that very soon, as part of the refactor process that we have been carry on in master for the last 2 weeks. ETA EOM.

**Comment by XAMeLi** [comment]
+1 facing the issue with Chinese (Simplified). For example: ‎2016‎年‎3月‎月‎29‎日
This is when using v1.1.0.
Any update on the ETA?

**Comment by shaosh** [comment]
I see the same issue with Simplified Chinese: day="numeric" month="long" year="numeric"
It returns ‎2016‎年‎4月‎月‎8‎日. 
I am using v1.1.0. This issue only happens to IE and Safari.

**Comment by watilde** [comment]
I could see this issue is fixed with the latest commit, but the last part was displayed different word. I think we should create a new issue and try to fix it.

```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var df = new IntlPolyfill.DateTimeFormat('zh', { year: "numeric", month: "long", day: "numeric", weekday: "long"});
console.log(
  df.format(date)
)
VM733:3 2012年12月20日周四
```

Well, probably the build commit fixes this issue: https://github.com/andyearnshaw/Intl.js/commit/ec3d98f1c3477a5058fc23dff37a9e09df1c3450

**Comment by okuryu** [comment]
Ha! This issue exactly seems to be fixed in the `master`. I've verified it works as expected on Node.js v0.10, v0.12, v4, and v6.

```bash
[okuryu.local](Intl.js@master)$ node
> require('./index')
{ getCanonicalLocales: [Function],
  __localeSensitiveProtos:
   { Number: { toLocaleString: [Function] },
     Date:
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } } }
> new IntlPolyfill.DateTimeFormat('ja', {year: "numeric", month: "long", day: "numeric", weekday: "long"}).format(Date.now())
'2016年5月1日(日)'
```

**Comment by caridy** [comment]
:) took some time, but it is now fixed. I plan to push the new version to npm on thru.

**Comment by caridy** [comment]
fixed by https://github.com/andyearnshaw/Intl.js/issues/171

**Comment by shaosh** [comment]
@caridy Which version contains the #171 fix?

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.1
